### ISSUE TITLE
Is it okay if I steal some of your bam-handling code and list you as a contributor to epic?

### ISSUE THREAD

**Issue by endrebak** [dariober/SICERpy#1]
Will add to README.md and make a contributors.TXT file in addition.

**Comment by endrebak** [comment]
If it is okay with you, I will just steal everything useful I see, but credit you for each feature/snippet.

**Comment by dariober** [comment]
Sure, don't even ask! 
(Thanks, I'm not sure I qualify as contributor to epic...!)
