### ISSUE TITLE
Can SICERpy be used for samples without control?

### ISSUE THREAD

**Issue by c-guzman** [dariober/SICERpy#7]
Was wondering if this wrapper can be used to call broad histone modifications for samples without input, MACS2 isn't very good at calling very diffuse peaks.

Thanks!

**Comment by dariober** [comment]
No, as far as I know, sicer needs the input and so does SICERpy.

**Comment by endrebak** [comment]
Sicer has a script caller sicer-rb for this, but the results do not seem
good to me. I did not bother implementing this in epic :)

Edit: it's not worse than other scripts that do not use input though. But ChIP-Seq is often 95% noise, so without input analyses are always suspect.
