### ISSUE TITLE
Can not pass species to SICER.py

### ISSUE THREAD

**Issue by ashrosewood** [dariober/SICERpy#8]
I just installed your latest version and noticed that I get the following error when I tried to use SICER.py while providing a species with the option --species as indicated on your readme. 
```
SICER.py: error: unrecognized arguments: --species hg19
```
I noticed if you look at the help from the command line, there is no species option available :
```
SICER.py -h
usage: SICER.py [-h] [--treatment TREATMENT] --control CONTROL
                [--effGenomeSize EFFGENOMESIZE] [--requiredFlag REQUIREDFLAG]
                [--filterFlag FILTERFLAG] [--mapq MAPQ]
                [--redThresh REDTHRESH] [--windowSize WINDOWSIZE]
                [--gapSize GAPSIZE] [--fragSize FRAGSIZE] [--keeptmp]
                [--version]
```

Could you look into this discrepancy?
Thanks,
Ashley

**Comment by dariober** [comment]
Hi- Indeed, the README file was outdated (now fixed). The `--species` option is no longer needed since chromosome sizes are extracted from the header of the input bam files. Thanks for reporting this!
