### ISSUE TITLE
remove redundant reads threshold

### ISSUE THREAD

**Issue by dinovski** [dariober/SICERpy#9]
Why has the option to remove redundant reads been commented out?

**Comment by dariober** [comment]
Hi- sorry I couldn't reply earlier. Can you point me to the part that has been commented out? Your question doesn't have enough information for me to understand what the issue is.

**Comment by dinovski** [comment]
Hi, lines 122 and 156-158 are commented out in SICER.py so the read threshold argument is not functional.

**Comment by dariober** [comment]
Hi- If you look at line 135 and 140 in [SICER.py](https://github.com/dariober/SICERpy/blob/a20ffffe9cee570902d334326ebb4d233f9b4814/SICERpy/SICER.py),  you can see that the read threshold `args.redThresh` is passed to the script `remove_redundant_reads_bam.py`. So yes, `args.redThresh` is still used. 

If you notice anything weird I'll investigate further how `remove_redundant_reads_bam.py` uses the `--threshold` argument (although `remove_redundant_reads_bam.py` comes from the original source of SICER)
